AutoMagazines/Controllers/ShopCartController.cs
using AutoMagazines.Data.DbContext;
using AutoMagazines.Data.Models.Cart;
using Microsoft.AspNetCore.Mvc;

namespace AutoMagazines.Controllers
{
    public class ShopCartController : Controller
    {
        StoreContext db;
        ShopCart _shopCart;
        public ShopCartController(StoreContext context, ShopCart shopCart)
        {
            db = context;
            _shopCart = shopCart;
        }

        public ViewResult Index()
        {

            _shopCart.ListShopItems = _shopCart.GetShopItems();
            return View(_shopCart.ListShopItems);
        }
        public void ClearCart()
        {
            // Используем ShopCartId из объекта _shopCart
            var cartItems = db.ShopCartItemTable.Where(c => c.ShopCartId == _shopCart.ShopCartId).ToList();
            db.ShopCartItemTable.RemoveRange(cartItems); // Удаляем все элементы корзины
            db.SaveChanges();
        }


        public RedirectToActionResult AddToCart(int id)
        {
            var item = db.CarTable.Find(id);
            if (item != null)
            {
                _shopCart.AddToCart(item);
            }
            return RedirectToAction("Index");
        }

    }
}

AutoMagazines/Views/Shared/Components/NavigationMenuViewComponent.cs
using AutoMagazines.Data.DbContext;
using Microsoft.AspNetCore.Mvc;

namespace AutoMagazines.Views.Shared.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        public StoreContext db;
        public NavigationMenuViewComponent(StoreContext context)
        {
            db = context;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["catId"];
            return View(db.CategoryTable.ToList());
        }
    }
}

AutoMagazines/Views/Home/Index.cshtml
@model AutoMagazines.Data.ViewModels.HomeIndexViewModel
<h2>@Model.PageName</h2>

<div class="row">
    <div class="col col-md-3">
        @await Component.InvokeAsync("NavigationMenu")
    </div>
    <div class="col col-md-10" >
        <div page-model="@Model.PagingInfo" page-action="Index"
             page-classes-enabled="true"
             page-class="btn" page-class-normal="btn-default"
             page-class-selected="btn-primary" class="btn-group pull-right">
        </div>
        <div class="row mt-5 mb-2">
            @{
                foreach (var car in Model.Cars)
                {
                    <div class="col-lg-4" >
                        <img style="width: 100%; border-radius:20px; height:180px" src="@car.Img" />
                        <h2>@car.Name</h2>
                        <p>@car.ShortDesc</p>
                        <p>Цена: @car.Price.ToString("c")</p>
                        <button class="btn btn-primary" href="#" onclick="location.href = '@Url.Action("SingleCar", "Car", new {carId=car.CarId})'">Подробнее</button>
                        <button class="btn btn-success" href="#" onclick="location.href = '@Url.Action("AddToCart", "ShopCart", new {id=car.CarId})'">В корзину</button>
                    </div>
                }
            }
        </div>
    </div>
</div>